ALTER TABLE "system_settings"
ADD COLUMN "loginFormLogoUrl" TEXT,
ADD COLUMN "loginLogoWidth" INTEGER NOT NULL DEFAULT 160,
ADD COLUMN "loginLogoHeight" INTEGER NOT NULL DEFAULT 48,
ADD COLUMN "loginFormLogoWidth" INTEGER NOT NULL DEFAULT 220,
ADD COLUMN "loginFormLogoHeight" INTEGER NOT NULL DEFAULT 72,
ADD COLUMN "brandTextSize" INTEGER NOT NULL DEFAULT 16,
ADD COLUMN "brandTextColor" TEXT NOT NULL DEFAULT '#ffffff';
