ALTER TABLE "system_settings"
ADD COLUMN "mobileLogoUrl" TEXT,
ADD COLUMN "mobileLoginLogoUrl" TEXT,
ADD COLUMN "appSubtitle" TEXT,
ADD COLUMN "showSubtitleOnLogin" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "showSubtitleInApp" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "subtitlePlacement" TEXT NOT NULL DEFAULT 'BELOW',
ADD COLUMN "mobileSubtitlePlacement" TEXT NOT NULL DEFAULT 'BELOW',
ADD COLUMN "subtitleSize" INTEGER NOT NULL DEFAULT 14,
ADD COLUMN "subtitleColor" TEXT NOT NULL DEFAULT '#cbd5e1',
ADD COLUMN "subtitleWeight" TEXT NOT NULL DEFAULT '400',
ADD COLUMN "subtitleStyle" TEXT NOT NULL DEFAULT 'normal',
ADD COLUMN "subtitleFontFamily" TEXT NOT NULL DEFAULT 'system',
ADD COLUMN "appBrandTextSize" INTEGER NOT NULL DEFAULT 16,
ADD COLUMN "appBrandTextColor" TEXT NOT NULL DEFAULT '#ffffff',
ADD COLUMN "mobileLogoWidth" INTEGER NOT NULL DEFAULT 34,
ADD COLUMN "mobileLogoHeight" INTEGER NOT NULL DEFAULT 34,
ADD COLUMN "mobileBrandTextSize" INTEGER NOT NULL DEFAULT 16,
ADD COLUMN "mobileBrandTextColor" TEXT NOT NULL DEFAULT '#ffffff',
ADD COLUMN "mobileLoginLogoWidth" INTEGER NOT NULL DEFAULT 140,
ADD COLUMN "mobileLoginLogoHeight" INTEGER NOT NULL DEFAULT 44,
ADD COLUMN "mobileLoginBrandTextSize" INTEGER NOT NULL DEFAULT 16,
ADD COLUMN "mobileLoginBrandTextColor" TEXT NOT NULL DEFAULT '#ffffff',
ADD COLUMN "brandFontFamily" TEXT NOT NULL DEFAULT 'system',
ADD COLUMN "loginHeadlineSize" INTEGER NOT NULL DEFAULT 48,
ADD COLUMN "loginHeadlineColor" TEXT NOT NULL DEFAULT '#ffffff',
ADD COLUMN "loginHeadlineWeight" TEXT NOT NULL DEFAULT '800',
ADD COLUMN "loginHeadlineStyle" TEXT NOT NULL DEFAULT 'normal',
ADD COLUMN "loginHeadlineFontFamily" TEXT NOT NULL DEFAULT 'system',
ADD COLUMN "loginSubtitleSize" INTEGER NOT NULL DEFAULT 18,
ADD COLUMN "loginSubtitleColor" TEXT NOT NULL DEFAULT '#ffffff',
ADD COLUMN "loginSubtitleWeight" TEXT NOT NULL DEFAULT '400',
ADD COLUMN "loginSubtitleStyle" TEXT NOT NULL DEFAULT 'normal',
ADD COLUMN "loginSubtitleAlign" TEXT NOT NULL DEFAULT 'left',
ADD COLUMN "loginSubtitleFontFamily" TEXT NOT NULL DEFAULT 'system',
ADD COLUMN "loginFooterSize" INTEGER NOT NULL DEFAULT 18,
ADD COLUMN "loginFooterColor" TEXT NOT NULL DEFAULT '#ffffff',
ADD COLUMN "loginFooterWeight" TEXT NOT NULL DEFAULT '400',
ADD COLUMN "loginFooterStyle" TEXT NOT NULL DEFAULT 'normal',
ADD COLUMN "loginFooterFontFamily" TEXT NOT NULL DEFAULT 'system';
