INSERT INTO "permissions" ("id", "name", "description", "createdAt", "updatedAt")
VALUES
  (md5('permission:users.view')::uuid, 'users.view', 'Allows users view', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:users.create')::uuid, 'users.create', 'Allows users create', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:users.update')::uuid, 'users.update', 'Allows users update', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:users.delete')::uuid, 'users.delete', 'Allows users delete', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:groups.view')::uuid, 'groups.view', 'Allows groups view', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:groups.create')::uuid, 'groups.create', 'Allows groups create', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:groups.update')::uuid, 'groups.update', 'Allows groups update', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:groups.delete')::uuid, 'groups.delete', 'Allows groups delete', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:roles.view')::uuid, 'roles.view', 'Allows roles view', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:roles.create')::uuid, 'roles.create', 'Allows roles create', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:roles.update')::uuid, 'roles.update', 'Allows roles update', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:roles.delete')::uuid, 'roles.delete', 'Allows roles delete', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:permissions.view')::uuid, 'permissions.view', 'Allows permissions view', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:clients.view')::uuid, 'clients.view', 'Allows clients view', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:clients.create')::uuid, 'clients.create', 'Allows clients create', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:clients.update')::uuid, 'clients.update', 'Allows clients update', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:clients.delete')::uuid, 'clients.delete', 'Allows clients delete', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:client_domains.view')::uuid, 'client_domains.view', 'Allows client domains view', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:client_domains.create')::uuid, 'client_domains.create', 'Allows client domains create', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:client_domains.update')::uuid, 'client_domains.update', 'Allows client domains update', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:client_domains.delete')::uuid, 'client_domains.delete', 'Allows client domains delete', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:contacts.view')::uuid, 'contacts.view', 'Allows contacts view', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:contacts.create')::uuid, 'contacts.create', 'Allows contacts create', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:contacts.update')::uuid, 'contacts.update', 'Allows contacts update', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:contacts.delete')::uuid, 'contacts.delete', 'Allows contacts delete', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:tickets.view')::uuid, 'tickets.view', 'Allows tickets view', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:tickets.create')::uuid, 'tickets.create', 'Allows tickets create', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:tickets.update')::uuid, 'tickets.update', 'Allows tickets update', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:tickets.assign')::uuid, 'tickets.assign', 'Allows tickets assign', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:tickets.reply')::uuid, 'tickets.reply', 'Allows tickets reply', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:tickets.close')::uuid, 'tickets.close', 'Allows tickets close', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:tickets.reopen')::uuid, 'tickets.reopen', 'Allows tickets reopen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:tickets.merge')::uuid, 'tickets.merge', 'Allows tickets merge', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:tickets.delete')::uuid, 'tickets.delete', 'Allows tickets delete', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:event_services.view')::uuid, 'event_services.view', 'Allows event services view', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:event_services.create')::uuid, 'event_services.create', 'Allows event services create', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:event_services.update')::uuid, 'event_services.update', 'Allows event services update', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:event_services.assign')::uuid, 'event_services.assign', 'Allows event services assign', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:event_services.manage_forms')::uuid, 'event_services.manage_forms', 'Allows event services manage forms', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:event_services.delete')::uuid, 'event_services.delete', 'Allows event services delete', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:external_specialists.view')::uuid, 'external_specialists.view', 'Allows external specialists view', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:external_specialists.manage')::uuid, 'external_specialists.manage', 'Allows external specialists manage', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:ticket_messages.view')::uuid, 'ticket_messages.view', 'Allows ticket messages view', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:ticket_messages.create_internal')::uuid, 'ticket_messages.create_internal', 'Allows ticket messages create internal', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:ticket_messages.create_public')::uuid, 'ticket_messages.create_public', 'Allows ticket messages create public', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:ticket_attachments.view')::uuid, 'ticket_attachments.view', 'Allows ticket attachments view', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:ticket_attachments.upload')::uuid, 'ticket_attachments.upload', 'Allows ticket attachments upload', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:ticket_attachments.download')::uuid, 'ticket_attachments.download', 'Allows ticket attachments download', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:ticket_attachments.delete')::uuid, 'ticket_attachments.delete', 'Allows ticket attachments delete', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:mailboxes.view')::uuid, 'mailboxes.view', 'Allows mailboxes view', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:mailboxes.create')::uuid, 'mailboxes.create', 'Allows mailboxes create', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:mailboxes.update')::uuid, 'mailboxes.update', 'Allows mailboxes update', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:mailboxes.delete')::uuid, 'mailboxes.delete', 'Allows mailboxes delete', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:spam.view')::uuid, 'spam.view', 'Allows spam view', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:spam.manage')::uuid, 'spam.manage', 'Allows spam manage', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:maintenance.view')::uuid, 'maintenance.view', 'Allows maintenance view', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:maintenance.manage')::uuid, 'maintenance.manage', 'Allows maintenance manage', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:auto_replies.view')::uuid, 'auto_replies.view', 'Allows auto replies view', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:auto_replies.create')::uuid, 'auto_replies.create', 'Allows auto replies create', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:auto_replies.update')::uuid, 'auto_replies.update', 'Allows auto replies update', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:auto_replies.delete')::uuid, 'auto_replies.delete', 'Allows auto replies delete', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:signatures.view')::uuid, 'signatures.view', 'Allows signatures view', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:signatures.update')::uuid, 'signatures.update', 'Allows signatures update', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:ai_assistant.use')::uuid, 'ai_assistant.use', 'Allows ai assistant use', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:ai_assistant.configure')::uuid, 'ai_assistant.configure', 'Allows ai assistant configure', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:knowledge_base.view')::uuid, 'knowledge_base.view', 'Allows knowledge base view', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:knowledge_base.create')::uuid, 'knowledge_base.create', 'Allows knowledge base create', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:knowledge_base.update')::uuid, 'knowledge_base.update', 'Allows knowledge base update', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:knowledge_base.delete')::uuid, 'knowledge_base.delete', 'Allows knowledge base delete', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:knowledge_base.publish')::uuid, 'knowledge_base.publish', 'Allows knowledge base publish', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:reports.view')::uuid, 'reports.view', 'Allows reports view', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:reports.export')::uuid, 'reports.export', 'Allows reports export', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:reports.manage')::uuid, 'reports.manage', 'Allows reports manage', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:reports.send')::uuid, 'reports.send', 'Allows reports send', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:devices.view')::uuid, 'devices.view', 'Allows devices view', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:devices.create')::uuid, 'devices.create', 'Allows devices create', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:devices.update')::uuid, 'devices.update', 'Allows devices update', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:devices.delete')::uuid, 'devices.delete', 'Allows devices delete', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:remote_access.view')::uuid, 'remote_access.view', 'Allows remote access view', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:remote_access.connect')::uuid, 'remote_access.connect', 'Allows remote access connect', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:remote_access.configure')::uuid, 'remote_access.configure', 'Allows remote access configure', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:audit_logs.view')::uuid, 'audit_logs.view', 'Allows audit logs view', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:audit_logs.export')::uuid, 'audit_logs.export', 'Allows audit logs export', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:system_settings.view')::uuid, 'system_settings.view', 'Allows system settings view', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (md5('permission:system_settings.update')::uuid, 'system_settings.update', 'Allows system settings update', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("name") DO UPDATE
SET "description" = EXCLUDED."description",
    "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "role_permissions" ("id", "roleId", "permissionId", "createdAt")
SELECT md5('role_permission:' || r."id"::text || ':' || p."id"::text)::uuid, r."id", p."id", CURRENT_TIMESTAMP
FROM "roles" r
CROSS JOIN "permissions" p
WHERE r."name" IN ('Super Admin', 'Admin')
  AND p."name" IN (
    'users.view', 'users.create', 'users.update', 'users.delete',
    'groups.view', 'groups.create', 'groups.update', 'groups.delete',
    'roles.view', 'roles.create', 'roles.update', 'roles.delete',
    'permissions.view', 'clients.view', 'clients.create', 'clients.update', 'clients.delete',
    'client_domains.view', 'client_domains.create', 'client_domains.update', 'client_domains.delete',
    'contacts.view', 'contacts.create', 'contacts.update', 'contacts.delete',
    'tickets.view', 'tickets.create', 'tickets.update', 'tickets.assign', 'tickets.reply', 'tickets.close', 'tickets.reopen', 'tickets.merge', 'tickets.delete',
    'event_services.view', 'event_services.create', 'event_services.update', 'event_services.assign', 'event_services.manage_forms', 'event_services.delete',
    'external_specialists.view', 'external_specialists.manage',
    'ticket_messages.view', 'ticket_messages.create_internal', 'ticket_messages.create_public',
    'ticket_attachments.view', 'ticket_attachments.upload', 'ticket_attachments.download', 'ticket_attachments.delete',
    'mailboxes.view', 'mailboxes.create', 'mailboxes.update', 'mailboxes.delete',
    'spam.view', 'spam.manage', 'maintenance.view', 'maintenance.manage',
    'auto_replies.view', 'auto_replies.create', 'auto_replies.update', 'auto_replies.delete',
    'signatures.view', 'signatures.update',
    'ai_assistant.use', 'ai_assistant.configure',
    'knowledge_base.view', 'knowledge_base.create', 'knowledge_base.update', 'knowledge_base.delete', 'knowledge_base.publish',
    'reports.view', 'reports.export', 'reports.manage', 'reports.send',
    'devices.view', 'devices.create', 'devices.update', 'devices.delete',
    'remote_access.view', 'remote_access.connect', 'remote_access.configure',
    'audit_logs.view', 'audit_logs.export',
    'system_settings.view', 'system_settings.update'
  )
ON CONFLICT ("roleId", "permissionId") DO NOTHING;
